version: "3"

services:
  mockServer:
    image: mendhak/http-https-echo

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  topic-producer:
    image: wurstmeister/kafka:2.11-1.1.1
    command: "bash -c 'for i in `seq 1 10000`;
                       do
                         echo \"{\\\"value\\\":$$i}\" | /opt/kafka/bin/kafka-console-producer.sh --broker-list kafka:9092 --topic test;
                         echo $$i;
                       done'"
    depends_on:
      - kafka

  webhook:
    image: graphpathai/kafka-simple-webhooks
    environment:
      kafka.topic: "test"
      kafka.application.id: "webhooks"
      kafka.bootstrap.servers: "kafka:9092"
      webhook.url: "http://mockServer/"
      webhook.headers.Content-Type: "application/json"
      webhook.headers.custom: "header"
      webhook.headers.Custom-Header: "2222"
    depends_on:
      - kafka
